name: AstronomiaPlugin
version: 1.1.1
main: com.beeleeong.minecraft.plugins.AstronomiaPlugin
commands:
  save-loc:
    description: Send your location to our amazing discord group
    usage: /save-loc "Description"
